---
common_timezone: UTC
common_packages:
  - curl
  - git
  - htop
  - jq
  - vim
  - net-tools
  - ca-certificates
common_kernel_modules:
  - overlay
  - br_netfilter
common_sysctl:
  net.ipv4.ip_forward: "1"
  net.bridge.bridge-nf-call-iptables: "1"
  net.bridge.bridge-nf-call-ip6tables: "1"
